languageCode = "en-us"
baseUrl = ""
title = "Ksrof's Blog"
theme = ["anubis", "plausible"]
paginate = 10
# disqusShortname = "yourdiscusshortname"
# googleAnalytics = "G-12345"
enableRobotsTXT = true

[[menu.main]]
identifier = "archive"
name = "Archive"
title = "Archive"
url = "/posts/"
weight = 0

[params]
author = "ksrof"
email = "itsksrof@proton.me"
# avatar = "images/me.png"
description = "Welcome to my little corner of the internet. I'm an Open Sourcerer who writes about code."
dateFormat = "02-01-2006"
paginationSinglePost = true
style = "dark-without-switcher"
readMore = true
readNextPosts = 5
disableSummary = false
copyCodeButton = true
rssAsSocialIcon = true
# mathjax = false
# utterancesRepo = ""
# utterancesTheme = ""
# utterancesIssue = ""
# utterancesLabel = ""
# graphcommentId = ""

# [params.isso]
# enabled = true
# data = "" 
# jsLocation = "https://comments.example.com/js/embed.min.js"
# css = true
# lang = "de"
# replyToSelf = true
# requireAuthor = true
# requireEmail = true
# id = "thread-id"
# avatar = true
# avatar-bg = "#f0f0f0"
# feed = false

# [params.UmamiAnalytics]
# enabled = true
# dnt = true
# id = "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
# datacache = false
# url = "https://abc.example.com/umami.js"

# [params.webmentions]
# url = "https://yourdomain.com/webemntions/receive"
# login = "hugo-theme-anubis"
# pingback = true

# [[params.social]]
# id = "github"
# name = "gohugoio"

[markup.goldmark.renderer]
unsafe = true

[params.plausible]
enable = true
domain = "ksrof.com"
proxy_netlify = true
outbound_link = false
file_downloads = false
debug = false
gitstar = false